fastn-stack/fastn.com

- crate/config.ftd
[Implementation PR](https://github.com/FifthTry/fpm/pull/157).
> `fpm::Config::read()` to take optional root parameter

- how-to/install.ftd
- Switching to bash for installing fpm in linux systems 
- To avoid backward-incompatibility issue with sh while executing install-fpm.sh
> Updating the doc to use bash instead of sh

- sitemap.ftd
- documentation update regarding the recent changes in sitemap in which the users 
can now use component `id` for linking.
> Docs added for sitemap linking using id

- featured/index.ftd
With this PR we have updated all fonts and now fonts are linked to `fastn-community` font packages.
We also removed color scheme links until its documentation is ready.
> Updating fonts and removing CS until next update on its docs

- FASTN.ftd
- best-practices/self-referencing.ftd
- blog/lib.ftd
- expander/basic-ui.ftd
- expander/button.ftd
- expander/events.ftd
- expander/hello-world.ftd
- expander/imagemodule/index.ftd
- ftd/document.ftd
- planning/button/index.ftd
In this Pull Request:
- The URLs are **shortened** eg: `/ftd/row/` has been shortened with `/row/`
- Created **redirect** for all such shortened URLs
- Also, the URLs are **updated** in all such documents that have used old URL.
> shortened url + redirect + updated url in documents

- FASTN/ds.ftd
fastn.com 404 issue is fixed using below image `.light` property.
optional ftd.raw-image-src document-image: $fastn-assets.files.images.fastn.svg.light
> fixing build issue

- FASTN.ftd
Added redirect to map `/learn/` to `/frontend/learn/`. 
We have two Learn subsections, the other is `/backend/learn/`.
> Redirect from `/learn` to `/frontend/learn/`

- FASTN/ds.ftd
Fixed component `page-with-get-started-and-no-right-sidebar`:
```ftd
-- component page-with-get-started-and-no-right-sidebar:
children uis:
optional caption title:
optional body body:
;; Changed `caption` and added `body` to the below page component
-- page: $page-with-get-started-and-no-right-sidebar.title
sidebar: false
right-sidebar: []
$page-with-get-started-and-no-right-sidebar.body     
-- ftd.column:
spacing.fixed.em: 0.8
width: fill-container
-- obj:
$loop$: $page-with-get-started-and-no-right-sidebar.uis as $obj
-- cl.get-started:
-- end: ftd.column
-- end: page
-- end: page-with-get-started-and-no-right-sidebar
```
> Fixed `FASTN/ds.ftd` component: `page-with-get-started-and-no-right-sidebar`

- content-library/compare.ftd
Under Compare subsection, `fastn Vs React` document, the default value of mutable variable `$show` was displaying `true` instead it should have been `false` in the rendered input code block.
Made that correction in this PR.
> minor input code-block fix

- expander/layout/index.ftd
The video was given the URL instead of just `v` value. Fixed.
> holy grail video fix

- FASTN.ftd
In this URL: https://fastn.com/docs/
The `Overview` hyperlink was giving Page not found. So redirected /overview/ to /home/
> /overview/ is redirected to /home/

- ftd/video.ftd
Fixed inconsistencies in rendered input and output and also elaborated the `controls` attribute in bit more detail with one more example where `controls` has been set to false.
> Fixed inconsistencies in rendered input and output

- install.sh
Fixed issues related to fastn installation on Mac and Linux
Fixes:
- check if we have neccessary permissions for performing the installation
- check if the PATH has been correctly set or not
- better logs
> Fixed issues related to fastn installation on Mac and Linux

- FASTN/ds.ftd
We have updated default github star banner with Book a demo text with AmitU's calendar link on it.
> Added AmitU calendar to banner and CTA updated

- install.sh
Create a shell configuration file if it doesn't already exist.
This addresses an issue raised by one of our Discord members (Username: envy.312) where, if the shell configuration file doesn't exist, instead of allowing it to fail, it will create the shell configuration file and then update it with the PATH variable.
> Fix: create shell config file if it didnt already exist

- ftd-host/import.ftd
In `fastn.com/import`:
- Corrected the wrong `code-block`.
- Improved documentation by giving bold to keyword and emphasis to highlight words.
> corrected code-block + improved import documentation

- FASTN.ftd
- author/setup/windows.ftd
1. Created a redirect entry:
```ftd
/setup.exe/ -> https://github.com/fastn-stack/fastn/releases/latest/download/fastn_setup.exe
```
2. Updated Windows Installation document and removed releases page hyperlink
> New redirect entry for /setup.exe/ & Updated windows installation

- install.sh
Simplified the installation script:
Simplifications:
- Use direct browser download URLs instead of using Github API and grep
- Use minimal branding in terminal
- removed unneccessary log messages, instead use error logs for debugging
Fixes:
- Handle exit on interruption (CTRL+C)
> Simplified the installation script

- workshop/learn.ftd
Improving `learn` page:
- added information about the `champion program`
- reordered the headings to move the developer part at the top
> Optimizing learn page 🚧

- ftd/video.ftd
Removed the third line `muted: true ;; <hl>` (already in line 2) in the `rendered.input` under `Muted` heading
> removed redundant code 

- .gitignore
added cache dir in .gitignore to prevent unneccessary cache files from being added in the commit. these cache folder/file names are unique for each system, and this PR only adds the ignores for Nandhini's system.
> added cache dir in .gitignore

- FASTN.ftd
- content-library/index.ftd
- why/geeks.ftd
Link to `/custom-urls/` in https://fastn.com/dynamic-urls/ (first paragraph) is broken as it's `/custom-url/` in FASTN.ftd. This fixes this and uses `/custom-urls` in all places.
> fix: consistent use of /custom-urls/

- FASTN.ftd
- backend/env-vars.ftd
- best-practices/env-vars.ftd
- ftd-host/pg.ftd
document https://github.com/fastn-stack/fastn/pull/1425
[Rendered](https://fastncom-git-fork-siddhantk232-doc-env-vars-fifthtry.vercel.app/env/)
> doc: env-vars

- content-library/index.ftd
> minor footer layout fixes

- author/how-to/vercel.ftd
- [fastn-template now has a `vercel.json` file](https://github.com/fastn-stack/fastn-template/commit/770a7f9cbc2265e1c6f4b567c4ee7e1a39c3d97c) which we can use to smooth the deployment process when using it to create new github repositories.
- We also mention the use of `vercel.json` file in this doc instead of going through the UI when deploying existing fastn projects to vercel.
> update vercel docs to use vercel.json file

- .github/dependabot.yml
- .github/workflows/deploy.yml
- Install fastn
- Checkout to the main branch
- Run fastn build with `offline` flag cause we don't have to download any package file again since they are already checked in
- publish the build artifacts to vh_page branch
> Update deploy.yml and added dependabot.yml
