crate/config.ftd
journal.ftd

[Implementation PR](https://github.com/FifthTry/fpm/pull/158).

root should be string

---

FPM/config.ftd
theme/space.ftd

 added ftd space

---

linking-guide.ftd
usage.ftd

- fixed `fpm` cli documents link
- Added linking guide

fixed fpm cli documents link

---

FPM.ftd

rename  Site Structure to  Sitemap

rename  Site Structure to  Sitemap

---

sitemap.ftd

Code commits: [565d96](https://github.com/FifthTry/fpm/commit/565d96c32a914bbb71365ee4d191fbeb5921b560) and [49c3ad5](https://github.com/FifthTry/fpm/commit/49c3ad5844181dfb217f7bb25445810bfe1cc10c)

Sitemap assets

---

FPM.ftd
FPM/config.ftd
processors/sitemap.ftd
sitemap.ftd

Sitemap: add other packages documents and create variant

---

FPM.ftd
start-project.ftd
usage.ftd

- **FPM Documentation** added for **start-project** command 
- Link to the original PR in FPM - https://github.com/FifthTry/fpm/pull/202

Fpm start project doc update

---

processors/get-data.ftd

documentation added for reading a data from json file.

Documentation of reading data from json file

---

FPM.ftd

added monospace font dependency

added monospace font dependency

---

FPM.ftd
dev/user-group.ftd
dev/user-identity.ftd
fpm-ftd-file.ftd
processors/user-group-by-id.ftd
processors/user-group.ftd
processors/user-groups.ftd
theme/fpm.ftd

[Code PR](https://github.com/FifthTry/fpm/pull/272)

`fpm` `user-group`

---

crate/package.ftd
fpm-ftd-file.ftd
theme/fpm.ftd

[Code PR](https://github.com/FifthTry/fpm/pull/278)

`readers` and `writers` in `fpm.sitemap`

---

FPM.ftd
processors/document-filename.ftd
processors/document-full-id.ftd
processors/document-id.ftd
processors/document-readers.ftd
processors/document-suffix.ftd
processors/document-writers.ftd

- [Code PR](https://github.com/FifthTry/fpm/pull/353/)

document id's processors

---

lib.ftd
select-book-theme.ftd

duplicate header fixes

---

FPM.ftd
abrar-scratch.ftd
crate/user-group-compat.ftd
crate/user-group-temp.ftd
crate/user-group.ftd
dev/user-group.ftd
dev/user-identity.ftd
processors/get-identities.ftd
sitemap.ftd
theme/fpm.ftd

[Code PR](https://github.com/FifthTry/fpm/pull/359/)

`get-identities` for `fpm` http request

---

FPM.ftd
best-practices.ftd

Created new `best-practices.ftd` file and linked it into themes.

Added best-practices file

---

all.ftd
how-to/create-font-package.ftd

@amitu with new UI created All `FTD` Components page:

added all components page with new ui

---

featured/test.ftd
select-book-theme.ftd
theme/type.ftd

- using same id on different components within the same package is forbidden now.
- refactoring the similar ones by numbering them

refactor for conflicting ids usage

---

FPM.ftd
crate/utils.ftd
sitemap/clear-cache.ftd

[Code](https://github.com/FifthTry/fpm/pull/467)
[Discussion](https://github.com/FifthTry/fpm/discussions/475)

API `clear-cache`

---

sitemap.ftd

[Code PR](https://github.com/ftd-lang/fpm/pull/554)

sitemap: custom url mapping with `document` parameter

---

sitemap.ftd

[Code](https://github.com/ftd-lang/fpm/pull/558)

sitemap: dynamic-parameters

---

processors/request-data.ftd

[Code](https://github.com/ftd-lang/fpm/pull/566)
[Discussion](https://github.com/ftd-lang/fpm/discussions/551)

Docs: Named Parameters in request-data processor

---

fpm-ftd-file.ftd
sitemap.ftd

[Code](https://github.com/ftd-lang/fpm/pull/582)

Doc: sitemap/dynamic-urls

---

fpm-ftd-file.ftd

[Code](https://github.com/ftd-lang/fpm/pull/587)

package dependency `mount-point`

---

FPM.ftd
apps.ftd

Code: https://github.com/ftd-lang/fpm/pull/618

processor/apps: fpm-app processor

---

apps.ftd
fpm-ftd-file.ftd

Code: https://github.com/ftd-lang/fpm/pull/630

fpm apps processor fixes

---

all.ftd

only description text is scrollable

only description text is scrollable

---

all.ftd

Added list of all component, template and theme

Added list of all component, template and theme

---

all.ftd

added more details

---

all.ftd

added last-upadated variable in packages component

added last-upadated variable in packages component

---

FPM/config.ftd
all.ftd
dev/fpm-heroku.ftd
featured/index.ftd
how-to/oauth/github/gh.ftd
how-to/translation.ftd
journal.ftd
lib.ftd
new/book.ftd
new/open-source.ftd
theme/type.ftd
vars.ftd

Upgrade code with typography and spacing

Upgrade code with typography and spacing

---

author/setup/macos.ftd
author/setup/windows.ftd
expander/components.ftd
expander/hello-world.ftd

Following are the changes in the installation pages:
- added hyperlinks for terminal documentation
- changed the position of the `.gif` image
- minor changes in documentation
Following are the changes in Expander:
- part 1 video updated

updated installation pages and added part 1 video in expander

---

best-practices.ftd

Added `id` attribute to `best-practice` component for anchor linking.

Added id attribute to best-practice component

---

FASTN.ftd
best-practices/formatting.ftd
best-practices/property-guidelines.ftd

draft property guidelines doc added
Others:
Removed unused package import line from formatting doc

added property guidelines and removed unused import from formatting

---

index.ftd

mobile compatibility fixes

---

featured/fonts.ftd
featured/index.ftd

With this PR we have added all available fonts from `fastn-community` we will keep updating this in future.

Added new fonts from fastn community

---

events/web-dev-using-ftd.ftd

Page for Web Development Session on 21st April

webdev-using-ftd-21st-April-2023

---

planning/button/index.ftd

Button video

---

FASTN.ftd
expander/imagemodule/index.ftd
expander/layout/index.ftd
expander/lib.ftd

- `adding images in modules` planning doc 
- final doc ready

images in the modules

---

FASTN.ftd
expander/ds/understanding-sitemap.ftd

`Understanding sitemap` document.
Added in sitemap:
- Video Course - frontend, build
- planning

Understanding sitemap doc

---

FASTN.ftd
best-practices/import-at-top.ftd
blog/meta-data-blog.ftd
expander/ds/markdown.ftd
expander/ds/meta-data.ftd

PR for the video: How to use markdown in `doc-site`.
Planning doc drafted.

docsite: markdown 🚧

---

FASTN.ftd
expander/ds/ds-page.ftd

Planning doc for the video How to create a page.

document for page component of doc-site

---

index.ftd

Open Source Framework is added in home page

Added Open Source 

---

featured/business-card/index.ftd
featured/index.ftd

With this change request, mobile UI of category listing page fixed.

Updated mobile UI of category listing page

---

featured/business-card/sample-real-demo.ftd
featured/business-card/sunset-card.ftd

Correction in link url spelling mistake

Correction in user manual link

---

FASTN.ftd

added `how to add color-scheme` doc in frontend

---

featured/business-card/card-1.ftd
featured/business-card/gradient-card.ftd
featured/business-card/midnight-card.ftd
featured/business-card/pattern-card.ftd
featured/business-card/sunset-card.ftd

With this PR we have fixed with issue of business card listing page page

fixing business card width issue

---

featured/index.ftd

with this PR we are fixing - template name not visible issue of mobile.

removing mouse-over title logic for mobile

---

featured/business-card/card-1.ftd
featured/business-card/gradient-card.ftd
featured/business-card/midnight-card.ftd
featured/business-card/pattern-card.ftd
featured/business-card/sunset-card.ftd

With this PR fixing business card landing page mobile view width of card image issue.

Fixing mobile view of business card landing page

---

FASTN.ftd
planning/country-details/index.ftd
planning/orientation-planning-video.ftd

To create a video on Orientation that will go above the series of video that one needs to create a website.
[Rendered Output](https://fastncom-git-orientation-planning-fifthtry.vercel.app/orientation-planning/)
Another document created for later use: country details

added Orientation Planning doc

---

featured/sections/heros/index.ftd
featured/sections/index.ftd

Updated sections library page links

Updated sections library page links

---

FASTN.ftd
featured/cs/blog-template-1-cs.ftd
featured/cs/blog-template-cs.ftd
featured/cs/blue-heal-cs.ftd
featured/cs/dark-flame-cs.ftd
featured/cs/forest-cs.ftd
featured/cs/index.ftd
featured/cs/little-blue-cs.ftd
featured/cs/midnight-storm-cs.ftd
featured/cs/misty-gray-cs.ftd
featured/cs/navy-nebula-cs.ftd
featured/cs/pink-tree-cs.ftd
featured/cs/pretty-cs.ftd
featured/cs/saturated-sunset-cs.ftd
featured/cs/yellow-lily-cs.ftd

With this CR we are updating all color scheme information template for featured page.

Updated all CS templates

---

featured/components/modals/alert-1.ftd
featured/components/modals/dialog-1.ftd
featured/components/modals/dialog-2.ftd
featured/components/modals/modal-1.ftd
featured/components/modals/modal-2.ftd

With this PR fixing 404 found.

Updated 404 links found

---

FASTN.ftd
featured/blog-templates.ftd
featured/blogs/blog-template-1.ftd
featured/blogs/blue-wave.ftd
featured/blogs/galaxia.ftd
featured/blogs/little-blue.ftd
featured/blogs/navy-nebula.ftd
featured/blogs/pink-tree.ftd
featured/blogs/yellow-lily.ftd
featured/landing/ct-landing.ftd
featured/landing/studious-couscous.ftd

With this PR we have updated landing and blog templates for featured page.

Updated landing and blog templates

---

featured/components-library.ftd
featured/components/bling/index.ftd
featured/components/business-cards/card-1.ftd
featured/components/business-cards/gradient-card.ftd
featured/components/business-cards/index.ftd
featured/components/business-cards/midnight-card.ftd
featured/components/business-cards/pattern-card.ftd
featured/components/business-cards/sample-real-demo.ftd
featured/components/business-cards/sunset-card.ftd
featured/components/buttons/index.ftd
featured/components/code-block.ftd
featured/components/footers/index.ftd
featured/components/headers/index.ftd
featured/components/modals/index.ftd
featured/cs/blog-template-1-cs.ftd
featured/cs/blog-template-cs.ftd
featured/cs/dark-flame-cs.ftd
featured/cs/forest-cs.ftd
featured/cs/index.ftd
featured/cs/little-blue-cs.ftd
featured/cs/midnight-storm-cs.ftd
featured/cs/misty-gray-cs.ftd
featured/cs/navy-nebula-cs.ftd
featured/cs/pink-tree-cs.ftd
featured/cs/pretty-cs.ftd
featured/cs/saturated-sunset-cs.ftd
featured/cs/winter-cs.ftd
featured/cs/yellow-lily-cs.ftd
featured/sections/heros/index.ftd

With this PR the `ftd` text is replaced with `fastn`.

Updated ftd to fastn

---

FASTN.ftd
users/index.ftd

I have collected all the resources in one document. 
This document is used as a planning for time being. Once decided by AmitU and Nandhini that this can be also used as the index of the Create Website flow, we can utilise the same content.
[Rendered Output](https://fastncom-git-video-series-fifthtry.vercel.app/create-website-planning/)

`create website` planning

---

planning/country-details/index.ftd
users/index.ftd

Creating planning doc for country-details

country details: A hands-on guide to Dynamic UI using REST API

---

featured/doc-sites.ftd

With this PR fixing image missing issue found on live.

fixing issue found image missing

---

featured/landing/ct-landing.ftd

Minor change in template name.

minor issue fixed

---

FASTN.ftd
featured/ds/api-ds.ftd
featured/ds/blue-sapphire-template.ftd
featured/ds/dash-dash-ds.ftd
featured/ds/forest-template.ftd
featured/ds/framework.ftd
featured/ds/midnight-storm.ftd
featured/ds/misty-gray.ftd
featured/ds/spider-book-ds.ftd
featured/landing/misty-gray-landing.ftd

with this pr added template names inside contributor section

Following template names inside contributor section

---

featured/sections/index.ftd
featured/website-categories.ftd

updated heros on sections page

Updated heros and resumes

---

FASTN.ftd
index.ftd
student-programs/ambassadors/all-ambassadors.ftd
student-programs/champions/all-champions.ftd
student-programs/champions/ayush-soni.ftd

with this pr we have updated navigation of students program

Featured blogs

---

FASTN.ftd

Updated the Champion and Ambassador program URLs. Mapped them using `ftd.redirect`
- `/student-programs/champion-program/` to `/champion-program/`
- `/student-programs/ambassador-program/` to `/ambassador-program/`
Also, the internal URLs are also updated and shortened to make them into good URLs.

reverted the bad urls with previous good urls

---

FASTN.ftd
featured/blogs/doc-site.ftd
featured/blogs/mg-blog.ftd
featured/blogs/mr-blog.ftd
featured/blogs/ms-blog.ftd
featured/ds/doc-site.ftd
featured/ds/midnight-storm.ftd
featured/ds/misty-gray.ftd
featured/ds/mr-ds.ftd
featured/landing/midnight-storm-landing.ftd
featured/landing/misty-gray-landing.ftd
featured/landing/mr-landing.ftd
featured/portfolios/texty-ps.ftd

With this PR removed `Use this template` CTA from all places.

removed use this template cta from existing places

---

featured/blogs/blog-components.ftd
featured/blogs/blue-wave.ftd
featured/blogs/dash-dash-ds.ftd
featured/blogs/doc-site.ftd
featured/blogs/galaxia.ftd
featured/blogs/little-blue.ftd
featured/blogs/mg-blog.ftd
featured/blogs/mr-blog.ftd
featured/blogs/ms-blog.ftd
featured/blogs/navy-nebula.ftd
featured/blogs/pink-tree.ftd
featured/blogs/rocky.ftd
featured/blogs/simple-blog.ftd
featured/blogs/yellow-lily.ftd

With this PR we have updated blog templates with contributor section new UI.

Updated blog pages with latest UI

---

FASTN/ds.ftd
blog/writer-journey.ftd

With this PR we have replace:
```ftd
-- ftd.iframe:
src: https://www.youtube.com/embed/tAxY8D1TRTo
width.fixed.px: 747
height.fixed.px: 420
```
with:
```ftd
-- ds.youtube:
v: tAxY8D1TRTo
```

removing iframe and using youtube component

---

FASTN/ds.ftd
compare/react.ftd
compare/webflow.ftd
content-library/index.ftd
utils.ftd

- Added page-with-get-started-and-no-right-sidebar component, used in compare/react.ftd and compare/webflow.ftd
- Rearranging components definitions in right files

New component for /compare/*

---

FASTN.ftd

Used `skip` feature to skip saurabh's page under champions sub-toc

skipped saurabh's page

---

FASTN.ftd
featured/index.ftd
featured/landing-pages.ftd
featured/landing/ct-landing.ftd
featured/landing/docusaurus-theme.ftd
featured/landing/forest-foss-template.ftd
featured/landing/midnight-storm-landing.ftd
featured/landing/misty-gray-landing.ftd
featured/landing/mr-landing.ftd
featured/landing/studious-couscous.ftd

Removed SPA word from all places in featured pages.

Removed SPA word from all places

---

featured/index.ftd
featured/sections/cards/card-1.ftd
featured/sections/cards/image-card-1.ftd
featured/sections/cards/image-gallery-ig.ftd
featured/sections/cards/imagen-ig.ftd

[Rendered Preview](https://fastncom-git-featuted-image-fixes-fifthtry.vercel.app/featured/)
fixed image stretching issue on featured pages

Featuted image fixes

---

backend/country-details/dynamic-country-list-page.ftd
planning/country-details/script2.ftd

added video in part 2 of the backend series

Part 2 video of backend series: Building dynamic country list page

---

ftd/variables.ftd

data modelling inline url fixed

---

FASTN.ftd
expander/ds/meta-data.ftd
ftd/video.ftd

Added docs for the `ftd.video` element that was added recently.

Added docs for ftd.video element

---

FASTN.ftd
ftd/local-storage.ftd

Added Documentation for Local Storage (`ftd.local_storage`)

Added Documentation for Local Storage

---

FASTN.ftd
ftd/local-storage.ftd

Fixed Text colors in Local storage

Fixed Text colors in Local storage

---

ftd/image.ftd
ftd/video.ftd

Added `loop` and `fit` properties on `ftd.video` and `ftd.image`

Added `loop` and `fit` properties on `ftd.video` and `ftd.image`

---

featured/components/business-cards/card-1.ftd
featured/components/business-cards/gradient-card.ftd
featured/components/business-cards/pattern-card.ftd
featured/components/business-cards/sunset-card.ftd

updated business card components

updated business card

---

FASTN.ftd
featured/index.ftd

As suggested by Harish, resume is moved inside website categories and removed workshop.

Updated placement of resumes

---

FASTN/ds.ftd

new banner

---

FASTN.ftd

With this PR fixed broken link of discord

Fixing discord broken link

---

content-library/compare.ftd
utils.ftd

With this PR we have fixed broken layout issue of compare pages.

Fixing broken pages of compare flow

---

FASTN.ftd
workshop/index.ftd

In Workshop material, skipped the remaining parts and added WIP icon after removing hyperlinks in the index.ftd

skipped remaining parts and removed hyperlinks

---

content-library/index.ftd

removed github star button as already we have banner on top.

removing star us on github button

---

expander/ds/meta-data.ftd

Fixed bug causing theme changes to disrupt line numbers in `ds.code`.

Fixed `<title>` escape issue

---

workshop/learn.ftd

Improved content of /learn/ material.

improved learning resource document

---

backend/index.ftd
blog/acme.ftd
deploy/index.ftd
features/design.ftd
frontend/index.ftd
get-started/browse-pick.ftd
index.ftd

[Rendered Version](https://fastncom-git-internal-pages-update-fifthtry.vercel.app/)

content updates

---

featured/ds/mr-ds.ftd

With this PR we are fixing issue of broken links raised on our discord channel by a user.

Fixing broken links of mr ds

---

ftd/attributes.ftd
ftd/utils.ftd

fixed white space issue

---

blog/acme.ftd
utils.ftd

added getting started section inside acme case study page

added getting started section inside acme case study page

---

ftd-host/accessing-files.ftd
ftd-host/accessing-fonts.ftd
ftd-host/import.ftd

added highlight feature in code block

---

author/setup/windows.ftd

Changes done to the windows install page as requested by AmitU.

minor changes

---

student-programs/lead.ftd

Made improvements in some paragraphs and words.
- stakeholder as a single word.
- gave some positive tone to a paragraph.
- improved the message of a few paragraphs.

Improvements in the leads document

---

author/how-to/install.ftd
author/setup/windows.ftd
student-programs/lead.ftd

This PR has two changes:
1. Improved `install` and `windows` installation pages
2. Improved leads pages

improved the windows URL and cta

---

FASTN.ftd

added redirect for whatsapp link (cet):
```ftd
/cet/ -> ‎https://chat.whatsapp.com/Iiv1klM3c2G3e6eb8kCDhJ
```

added redirect for whatsapp link (cet)

---

content-library/index.ftd

fixed testimonial component width

fixed testimonial component width

---

FASTN.ftd

aieee vizag whatsapp redirect added.
/aieee-vizag/ -> https://chat.whatsapp.com/HigWcqIijQj63xCNAWJmLS

aieee vizag whatsapp redirect

---

ftd/built-in-types.ftd

replaced the word `ftd` with `fastn`

`ftd` replaced with `fastn`

---

FASTN.ftd
FASTN/ds.ftd
index.ftd

added learn links

---

ftd-host/pg.ftd

A bunch of environment variables are being added in https://github.com/fastn-stack/fastn/pull/1382, this PR documents them.

documented postgresql env variables

---

FASTN.ftd

- WhatsApp
- LinkedIn
- Github
- Instagram
- Twitter

added all socials

---

author/setup/uninstall.ftd

Added the uninstall `in windows` text.

updated uninstall in windows

---

.gitignore

.gitignore for cache dirs

---

author/how-to/install.ftd

Add Nix/NixOS flake installation instructions

---

ftd/built-in-types.ftd
ftd/common.ftd

documentation for the `mask` property and related records/or-types.

documentation for the `mask` property and related records/or-types.

---

install.sh

removing controller stuff from install.sh

---

FASTN.ftd
backend/env-vars.ftd
ftd-host/auth.ftd

Add a guide on how to use the `user-details` processor.
[Preview](https://fastncom-git-fork-siddhantk232-doc-user-details-fifthtry.vercel.app/auth/)

doc github auth

---

featured/portfolios/portfolio.ftd

updated featured portfolio URL

updated featured portfolio URL

---

featured/portfolios/portfolio.ftd

Updated portfolio url

---

FASTN.ftd
blog/content-library.ftd
blog/index.ftd

[Rendered](https://fastncom-git-blog-content-library-fifthtry.vercel.app/blog/content-library/)

new blog  - content library

---

ftd/built-in-types.ftd

added the dvh , lvh , svh in the built-in-type to support the web page through these units

dvh , svh , lvh added in built-in-types
